# generate keys:
# mkdir config
# openssl req -new -x509 -days 36500 -nodes -out config/nginx.pem \
#     -keyout config/nginx.key -subj "/C=US/CN=gitlab/O=gitlab.com"
gitlab:
    image: gitlab/gitlab-ce:11.3.6-ce.0
    restart: always
    hostname: '608.tuohn.com'
    environment:
        GITLAB_OMNIBUS_CONFIG: |
            external_url 'https://608.tuohn.com'
            nginx['redirect_http_to_https'] = true
            letsencrypt['enable'] = false
            nginx['ssl_certificate'] = "/etc/gitlab/nginx.pem"
            nginx['ssl_certificate_key'] = "/etc/gitlab/nginx.key"
            # Add any other gitlab.rb configuration here, each on its own line
    ports:
        - 443:443
        - 80:80
    volumes:
        - ./data:/var/opt/gitlab
        - ./logs:/var/log/gitlab
        - ./config:/etc/gitlab
