version: "2"

services:

    gitlab:
        image: gitlab/gitlab-ce:11.3.6-ce.0
        restart: always
        hostname: '608.tuohn.com'
        environment:
            GITLAB_OMNIBUS_CONFIG: |
                external_url 'https://608.tuohn.com:7583'
                nginx['redirect_http_to_https'] = true
                letsencrypt['enable'] = false
                nginx['ssl_certificate'] = "/etc/gitlab/ssl/nginx.pem"
                nginx['ssl_certificate_key'] = "/etc/gitlab/ssl/nginx.key"
                # Add any other gitlab.rb configuration here, each on its own line
        ports:
            - 7583:7583
        volumes:
            - ./data:/var/opt/gitlab
            - ./logs:/var/log/gitlab
            - ./config:/etc/gitlab
